# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-anvil-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True
